<h1><b>Airbnb Data Cleaning</h1>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv(r"D:\Airbnb_Open_Data.csv", low_memory=False)
df

'''
low_memory=False ---> If you're dealing with large files, pandas tries to optimize memory 
                      usage, which might cause issues with column type inference
'''

"\nlow_memory=False ---> If you're dealing with large files, pandas tries to optimize memory \n                      usage, which might cause issues with column type inference\n"

In [3]:
df

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN,NaN

In [4]:
df.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   NAME                            102349 non-null  object
 2   host id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  object
 4   host name                       102193 non-null  object
 5   neighbourhood group             102570 non-null  object
 6   neighbourhood                   102583 non-null  object
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  object
 10  country code                    102468 non-null  object
 11  instant_bookable                102494 non-null  object
 12  cancellation_policy             102523 non-null  object
 13  room type                       102599 non-null  object
 14  Construction year               102385 non-null  float64
 15  price                           102352 non-null  object
 16  service fee                     102326 non-null  object
 17  minimum nights                  102190 non-null  float64
 18  number of reviews               102416 non-null  float64
 19  last review                     86706 non-null   object
 20  reviews per month               86720 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102280 non-null  float64
 23  availability 365                102151 non-null  float64
 24  house_rules                     50468 non-null   object
 25  license                         2 non-null       object
dtypes: float64(9), int64(2), object(15)
memory usage: 20.4+ MB

In [6]:
df.describe(include='all')

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
count,1.025990e+05,102349,1.025990e+05,102310,102193,102570,102583,102591.000000,102591.000000,102067,...,102326,102190.000000,102416.000000,86706,86720.000000,102273.000000,102280.000000,102151.000000,50468,2
unique,NaN,61281,NaN,2,13190,7,224,NaN,NaN,1,...,231,NaN,NaN,2477,NaN,NaN,NaN,NaN,1976,1
top,NaN,Home away from home,NaN,unconfirmed,Michael,Manhattan,Bedford-Stuyvesant,NaN,NaN,United States,...,$41,NaN,NaN,6/23/2019,NaN,NaN,NaN,NaN,#NAME?,41662/AL
freq,NaN,33,NaN,51200,881,43792,7937,NaN,NaN,102067,...,526,NaN,NaN,2443,NaN,NaN,NaN,NaN,2712,2
mean,2.914623e+07,NaN,4.925411e+10,NaN,NaN,NaN,NaN,40.728094,-73.949644,NaN,...,NaN,8.135845,27.483743,NaN,1.374022,3.279106,7.936605,141.133254,NaN,NaN
std,1.625751e+07,NaN,2.853900e+10,NaN,NaN,NaN,NaN,0.055857,0.049521,NaN,...,NaN,30.553781,49.508954,NaN,1.746621,1.284657,32.218780,135.435024,NaN,NaN
min,1.001254e+06,NaN,1.236005e+08,NaN,NaN,NaN,NaN,40.499790,-74.249840,NaN,...,NaN,-1223.000000,0.000000,NaN,0.010000,1.000000,1.000000,-10.000000,NaN,NaN
25%,1.508581e+07,NaN,2.458333e+10,NaN,NaN,NaN,NaN,40.688740,-73.982580,NaN,...,NaN,2.000000,1.000000,NaN,0.220000,2.000000,1.000000,3.000000,NaN,NaN
50%,2.913660e+07,NaN,4.911774e+10,NaN,NaN,NaN,NaN,40.722290,-73.954440,NaN,...,NaN,3.000000,7.000000,NaN,0.740000,3.000000,1.000000,96.000000,NaN,NaN
75%,4.320120e+07,NaN,7.399650e+10,NaN,NaN,NaN,NaN,40.762760,-73.932350,NaN,...,NaN,5.000000,30.000000,NaN,2.000000,4.000000,2.000000,269.000000,NaN,NaN
max,5.736742e+07,NaN,9.876313e+10,NaN,NaN,NaN,NaN,40.916970,-73.705220,NaN,...,NaN,5645.000000,1024.000000,NaN,90.000000,5.000000,332.000000,3677.000000,NaN,NaN

In [7]:
# there's only 2 rows in the enire dataset. it's better to drop this column
df['license'].count()

2

---

<h2>Deleting Redundant Columns</h2>

In [8]:
df.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='object')

**********

<i>Divide the columns to keep & drop</i>

In [9]:
col_to_keep=['NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review']

col_to_drop=['id','reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license']

In [10]:
len(col_to_keep)

19

In [11]:
len(col_to_drop)

7

In [12]:
# 1st method --> by updating the col_to_keep to df

df=df[col_to_keep]
df

,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/2022
2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,2005.0,$620,$124,3.0,0.0,NaN
3,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0,7/5/2019
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,US,False,flexible,Private room,2003.0,$844,$169,1.0,0.0,NaN
102595,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,US,True,moderate,Private room,2016.0,$837,$167,1.0,1.0,7/6/2015
102596,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,US,True,moderate,Private room,2009.0,$988,$198,3.0,0.0,NaN
102597,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,US,True,strict,Entire home/apt,2015.0,$546,$109,2.0,5.0,10/11/2015
102598,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,US,False,flexible,Entire home/apt,2010.0,"$1,032",$206,1.0,0.0,NaN

In [13]:
# 2nd method --> by dropping the col

df.drop(columns = col_to_drop)  # returns error, bcz it's already updated by the 1st method
df

KeyError: "['id', 'reviews per month', 'review rate number', 'calculated host listings count', 'availability 365', 'house_rules', 'license'] not found in axis"

In [14]:
df.shape

(102599, 19)

***

<h2>Renaming/Formatting the columns</h2>

In [15]:
df.columns

Index(['NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review'],
      dtype='object')

In [16]:
# to rename the column
df.rename(columns={'NAME':'Name'},inplace=True)
df

C:\Users\karth\AppData\Local\Temp\ipykernel_10064\3996936639.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={'NAME':'Name'},inplace=True)

,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/2022
2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,2005.0,$620,$124,3.0,0.0,NaN
3,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0,7/5/2019
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,US,False,flexible,Private room,2003.0,$844,$169,1.0,0.0,NaN
102595,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,US,True,moderate,Private room,2016.0,$837,$167,1.0,1.0,7/6/2015
102596,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,US,True,moderate,Private room,2009.0,$988,$198,3.0,0.0,NaN
102597,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,US,True,strict,Entire home/apt,2015.0,$546,$109,2.0,5.0,10/11/2015
102598,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,US,False,flexible,Entire home/apt,2010.0,"$1,032",$206,1.0,0.0,NaN

In [17]:
# to rename the entire column
# create a empty list, format the col-names & append to the list
formatted_col=[]

for i in df.columns:
    formatted_col.append(i.capitalize())  # apply lower(),capitalize()

In [18]:
formatted_col

['Name',
 'Host id',
 'Host_identity_verified',
 'Host name',
 'Neighbourhood group',
 'Neighbourhood',
 'Lat',
 'Long',
 'Country',
 'Country code',
 'Instant_bookable',
 'Cancellation_policy',
 'Room type',
 'Construction year',
 'Price',
 'Service fee',
 'Minimum nights',
 'Number of reviews',
 'Last review']

In [19]:
# replaces the existing column headers with the new names
df.columns=formatted_col
df

,Name,Host id,Host_identity_verified,Host name,Neighbourhood group,Neighbourhood,Lat,Long,Country,Country code,Instant_bookable,Cancellation_policy,Room type,Construction year,Price,Service fee,Minimum nights,Number of reviews,Last review
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/2022
2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,2005.0,$620,$124,3.0,0.0,NaN
3,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0,7/5/2019
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,US,False,flexible,Private room,2003.0,$844,$169,1.0,0.0,NaN
102595,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,US,True,moderate,Private room,2016.0,$837,$167,1.0,1.0,7/6/2015
102596,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,US,True,moderate,Private room,2009.0,$988,$198,3.0,0.0,NaN
102597,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,US,True,strict,Entire home/apt,2015.0,$546,$109,2.0,5.0,10/11/2015
102598,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,US,False,flexible,Entire home/apt,2010.0,"$1,032",$206,1.0,0.0,NaN

----

<h2>Drop Duplicates</h2>

In [20]:
# to identifies the duplicate values in the dataset
df.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
102594     True
102595     True
102596     True
102597     True
102598     True
Length: 102599, dtype: bool

In [21]:
# returns the no. of duplicates
df.duplicated().sum()

541

In [22]:
# count the occurrences of each unique value in a column
df.duplicated().value_counts()

False    102058
True        541
Name: count, dtype: int64

In [23]:
# drops the duplicated values
df.drop_duplicates(inplace=True)
df

C:\Users\karth\AppData\Local\Temp\ipykernel_10064\968934309.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)

,Name,Host id,Host_identity_verified,Host name,Neighbourhood group,Neighbourhood,Lat,Long,Country,Country code,Instant_bookable,Cancellation_policy,Room type,Construction year,Price,Service fee,Minimum nights,Number of reviews,Last review
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/2022
2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,2005.0,$620,$124,3.0,0.0,NaN
3,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0,7/5/2019
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102053,Cozy bright room near Prospect Park,77326652202,unconfirmed,Mariam,Brooklyn,Flatbush,40.64945,-73.96108,United States,US,True,moderate,Private room,NaN,$696,NaN,7.0,12.0,3/27/2019
102054,Private Bedroom with Amazing Rooftop View,45936254757,verified,Trey,Brooklyn,Bushwick,40.69872,-73.92718,United States,US,False,flexible,Private room,NaN,$909,NaN,1.0,19.0,8/31/2017
102055,Pretty Brooklyn One-Bedroom for 2 to 4 people,23801060917,verified,Michael,Brooklyn,Bedford-Stuyvesant,40.67810,-73.90822,United States,US,True,moderate,Entire home/apt,NaN,$387,NaN,2.0,50.0,6/26/2019
102056,Room & private bathroom in historic Harlem,15593031571,unconfirmed,Shireen,Manhattan,Harlem,40.81248,-73.94317,United States,US,True,strict,Private room,NaN,$848,NaN,2.0,0.0,NaN
102057,Rosalee Stewart,93578954226,verified,Stanley,Manhattan,Harlem,40.81315,-73.94747,United States,US,False,flexible,Entire home/apt,2011.0,"$1,128",NaN,4.0,22.0,6/15/2019

In [24]:
df.duplicated().sum()  # no. of duplicates

0

In [25]:
df.duplicated().count()   # returns the count of non-null values

102058

-----

<h2>Remove NaN Values</h2>

In [26]:
df.isna().sum()

Name                        250
Host id                       0
Host_identity_verified      289
Host name                   404
Neighbourhood group          29
Neighbourhood                16
Lat                           8
Long                          8
Country                     532
Country code                131
Instant_bookable            105
Cancellation_policy          76
Room type                     0
Construction year           214
Price                       247
Service fee                 273
Minimum nights              400
Number of reviews           183
Last review               15832
dtype: int64

In [27]:
df.drop(columns=['Last review'], inplace=True)  # bcz of 15832 null values

C:\Users\karth\AppData\Local\Temp\ipykernel_10064\3197086075.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=['Last review'], inplace=True)  # bcz of 15832 null values

In [28]:
df.isna().sum()

Name                      250
Host id                     0
Host_identity_verified    289
Host name                 404
Neighbourhood group        29
Neighbourhood              16
Lat                         8
Long                        8
Country                   532
Country code              131
Instant_bookable          105
Cancellation_policy        76
Room type                   0
Construction year         214
Price                     247
Service fee               273
Minimum nights            400
Number of reviews         183
dtype: int64

In [29]:
# drops the row which contains null values in the dataset
df.dropna(inplace=True)
df

C:\Users\karth\AppData\Local\Temp\ipykernel_10064\1439186375.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(inplace=True)

,Name,Host id,Host_identity_verified,Host name,Neighbourhood group,Neighbourhood,Lat,Long,Country,Country code,Instant_bookable,Cancellation_policy,Room type,Construction year,Price,Service fee,Minimum nights,Number of reviews
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0
5,Large Cozy 1 BR Apartment In Midtown East,45498551794,verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,True,flexible,Entire home/apt,2013.0,$577,$115,3.0,74.0
7,BlissArtsSpace!,90821839709,unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,False,moderate,Private room,2009.0,"$1,060",$212,45.0,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102029,Cozy room in a 2B with backyard access,5155155913,unconfirmed,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,False,flexible,Private room,2018.0,$822,$164,1.0,9.0
102030,An East Williamsburg Delight,71564706996,verified,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,True,moderate,Private room,2015.0,$455,$91,4.0,36.0
102031,Cozy bedroom in williamsburg,83101851929,verified,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,True,flexible,Private room,2020.0,"$1,078",$216,1.0,58.0
102032,Spacious Room w/ 2 Bed,69037598918,unconfirmed,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,False,moderate,Private room,2007.0,$103,$21,7.0,40.0
102040,"Room in Queens, NY, near LGA.",56457739998,verified,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,True,strict,Private room,2022.0,$982,$196,1.0,239.0

In [30]:
df.isna().sum()

Name                      0
Host id                   0
Host_identity_verified    0
Host name                 0
Neighbourhood group       0
Neighbourhood             0
Lat                       0
Long                      0
Country                   0
Country code              0
Instant_bookable          0
Cancellation_policy       0
Room type                 0
Construction year         0
Price                     0
Service fee               0
Minimum nights            0
Number of reviews         0
dtype: int64

-----

<h2>Cleaning individual columns</h2>

In [31]:
df

,Name,Host id,Host_identity_verified,Host name,Neighbourhood group,Neighbourhood,Lat,Long,Country,Country code,Instant_bookable,Cancellation_policy,Room type,Construction year,Price,Service fee,Minimum nights,Number of reviews
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0
5,Large Cozy 1 BR Apartment In Midtown East,45498551794,verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,True,flexible,Entire home/apt,2013.0,$577,$115,3.0,74.0
7,BlissArtsSpace!,90821839709,unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,False,moderate,Private room,2009.0,"$1,060",$212,45.0,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102029,Cozy room in a 2B with backyard access,5155155913,unconfirmed,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,False,flexible,Private room,2018.0,$822,$164,1.0,9.0
102030,An East Williamsburg Delight,71564706996,verified,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,True,moderate,Private room,2015.0,$455,$91,4.0,36.0
102031,Cozy bedroom in williamsburg,83101851929,verified,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,True,flexible,Private room,2020.0,"$1,078",$216,1.0,58.0
102032,Spacious Room w/ 2 Bed,69037598918,unconfirmed,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,False,moderate,Private room,2007.0,$103,$21,7.0,40.0
102040,"Room in Queens, NY, near LGA.",56457739998,verified,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,True,strict,Private room,2022.0,$982,$196,1.0,239.0

In [32]:
# 'Host_identity_verified' --> formatting to upper()
df['Host_identity_verified']=df['Host_identity_verified'].str.upper()

C:\Users\karth\AppData\Local\Temp\ipykernel_10064\3739868098.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Host_identity_verified']=df['Host_identity_verified'].str.upper()

In [33]:
# 'Cancellation_policy' --> formatting to capitallize()
df['Cancellation_policy']=df['Cancellation_policy'].str.capitalize()

C:\Users\karth\AppData\Local\Temp\ipykernel_10064\2181540063.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Cancellation_policy']=df['Cancellation_policy'].str.capitalize()

In [34]:
df

,Name,Host id,Host_identity_verified,Host name,Neighbourhood group,Neighbourhood,Lat,Long,Country,Country code,Instant_bookable,Cancellation_policy,Room type,Construction year,Price,Service fee,Minimum nights,Number of reviews
0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,Strict,Private room,2020.0,$966,$193,10.0,9.0
1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,Moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,Moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0
5,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,True,Flexible,Entire home/apt,2013.0,$577,$115,3.0,74.0
7,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,False,Moderate,Private room,2009.0,"$1,060",$212,45.0,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102029,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,False,Flexible,Private room,2018.0,$822,$164,1.0,9.0
102030,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,True,Moderate,Private room,2015.0,$455,$91,4.0,36.0
102031,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,True,Flexible,Private room,2020.0,"$1,078",$216,1.0,58.0
102032,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,False,Moderate,Private room,2007.0,$103,$21,7.0,40.0
102040,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,True,Strict,Private room,2022.0,$982,$196,1.0,239.0

In [38]:
# 'Construction year' --> removing '.0' in the year ie (2022.0)
# 1. change the datatype to str to perform replace()

df['Construction year']=df['Construction year'].astype(str)

C:\Users\karth\AppData\Local\Temp\ipykernel_10064\2847475510.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Construction year']=df['Construction year'].astype(str)

In [39]:
df.dtypes

Name                       object
Host id                     int64
Host_identity_verified     object
Host name                  object
Neighbourhood group        object
Neighbourhood              object
Lat                       float64
Long                      float64
Country                    object
Country code               object
Instant_bookable           object
Cancellation_policy        object
Room type                  object
Construction year          object
Price                      object
Service fee                object
Minimum nights            float64
Number of reviews         float64
dtype: object

In [40]:
df['Construction year']=df['Construction year'].str.replace('.0','',regex=False)
df

C:\Users\karth\AppData\Local\Temp\ipykernel_10064\1515986502.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Construction year']=df['Construction year'].str.replace('.0','',regex=False)

,Name,Host id,Host_identity_verified,Host name,Neighbourhood group,Neighbourhood,Lat,Long,Country,Country code,Instant_bookable,Cancellation_policy,Room type,Construction year,Price,Service fee,Minimum nights,Number of reviews
0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,Strict,Private room,2020,$966,$193,10.0,9.0
1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,Moderate,Entire home/apt,2007,$142,$28,30.0,45.0
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,Moderate,Entire home/apt,2009,$204,$41,10.0,9.0
5,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,True,Flexible,Entire home/apt,2013,$577,$115,3.0,74.0
7,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,False,Moderate,Private room,2009,"$1,060",$212,45.0,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102029,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,False,Flexible,Private room,2018,$822,$164,1.0,9.0
102030,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,True,Moderate,Private room,2015,$455,$91,4.0,36.0
102031,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,True,Flexible,Private room,2020,"$1,078",$216,1.0,58.0
102032,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,False,Moderate,Private room,2007,$103,$21,7.0,40.0
102040,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,True,Strict,Private room,2022,$982,$196,1.0,239.0

In [41]:
# 'Price & Service fee' --> replacing '$,' by blank space, to perform numeric operations 

df['Price']=df['Price'].str.replace(',','',regex=False)
df['Price']=df['Price'].str.replace('$','',regex=False)

df['Service fee']=df['Service fee'].str.replace('[$,]','',regex=True)
df
# other way by giving the character in list & assigning 'regex=True'
# df['Price']=df['Price'].str.replace('[$,]','',regex=True)

C:\Users\karth\AppData\Local\Temp\ipykernel_10064\3463712355.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Price']=df['Price'].str.replace(',','',regex=False)
C:\Users\karth\AppData\Local\Temp\ipykernel_10064\3463712355.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Price']=df['Price'].str.replace('$','',regex=False)
C:\Users\karth\AppData\Local\Temp\ipykernel_10064\3463712355.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Service fee']=df['Service fee'].str.replace('[$,]','',regex=True)

,Name,Host id,Host_identity_verified,Host name,Neighbourhood group,Neighbourhood,Lat,Long,Country,Country code,Instant_bookable,Cancellation_policy,Room type,Construction year,Price,Service fee,Minimum nights,Number of reviews
0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,Strict,Private room,2020,966,193,10.0,9.0
1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,Moderate,Entire home/apt,2007,142,28,30.0,45.0
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,Moderate,Entire home/apt,2009,204,41,10.0,9.0
5,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,True,Flexible,Entire home/apt,2013,577,115,3.0,74.0
7,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,False,Moderate,Private room,2009,1060,212,45.0,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102029,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,False,Flexible,Private room,2018,822,164,1.0,9.0
102030,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,True,Moderate,Private room,2015,455,91,4.0,36.0
102031,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,True,Flexible,Private room,2020,1078,216,1.0,58.0
102032,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,False,Moderate,Private room,2007,103,21,7.0,40.0
102040,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,True,Strict,Private room,2022,982,196,1.0,239.0

In [42]:
df['Service fee']

0         193
1          28
4          41
5         115
7         212
          ...
102029    164
102030     91
102031    216
102032     21
102040    196
Name: Service fee, Length: 99342, dtype: object

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 99342 entries, 0 to 102040
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    99342 non-null  object
 1   Host id                 99342 non-null  int64
 2   Host_identity_verified  99342 non-null  object
 3   Host name               99342 non-null  object
 4   Neighbourhood group     99342 non-null  object
 5   Neighbourhood           99342 non-null  object
 6   Lat                     99342 non-null  float64
 7   Long                    99342 non-null  float64
 8   Country                 99342 non-null  object
 9   Country code            99342 non-null  object
 10  Instant_bookable        99342 non-null  object
 11  Cancellation_policy     99342 non-null  object
 12  Room type               99342 non-null  object
 13  Construction year       99342 non-null  object
 14  Price                   99342 non-null  object
 15  Service fee             99342 non-null  object
 16  Minimum nights          99342 non-null  float64
 17  Number of reviews       99342 non-null  float64
dtypes: float64(4), int64(1), object(13)
memory usage: 14.4+ MB

In [44]:
# converted float to int datatype
df[['Minimum nights','Number of reviews']]=df[['Minimum nights','Number of reviews']].astype(int)
df

C:\Users\karth\AppData\Local\Temp\ipykernel_10064\4121676526.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['Minimum nights','Number of reviews']]=df[['Minimum nights','Number of reviews']].astype(int)

,Name,Host id,Host_identity_verified,Host name,Neighbourhood group,Neighbourhood,Lat,Long,Country,Country code,Instant_bookable,Cancellation_policy,Room type,Construction year,Price,Service fee,Minimum nights,Number of reviews
0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,Strict,Private room,2020,966,193,10,9
1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,Moderate,Entire home/apt,2007,142,28,30,45
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,Moderate,Entire home/apt,2009,204,41,10,9
5,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,True,Flexible,Entire home/apt,2013,577,115,3,74
7,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,False,Moderate,Private room,2009,1060,212,45,49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102029,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,False,Flexible,Private room,2018,822,164,1,9
102030,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,True,Moderate,Private room,2015,455,91,4,36
102031,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,True,Flexible,Private room,2020,1078,216,1,58
102032,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,False,Moderate,Private room,2007,103,21,7,40
102040,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,True,Strict,Private room,2022,982,196,1,239

In [45]:
# converted True/False to 1-0's
df['Instant_bookable']=df['Instant_bookable'].apply(lambda x: 1 if x==True else 0)
df

C:\Users\karth\AppData\Local\Temp\ipykernel_10064\2123880604.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Instant_bookable']=df['Instant_bookable'].apply(lambda x: 1 if x==True else 0)

,Name,Host id,Host_identity_verified,Host name,Neighbourhood group,Neighbourhood,Lat,Long,Country,Country code,Instant_bookable,Cancellation_policy,Room type,Construction year,Price,Service fee,Minimum nights,Number of reviews
0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,Strict,Private room,2020,966,193,10,9
1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,Moderate,Entire home/apt,2007,142,28,30,45
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,Moderate,Entire home/apt,2009,204,41,10,9
5,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,1,Flexible,Entire home/apt,2013,577,115,3,74
7,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,Moderate,Private room,2009,1060,212,45,49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102029,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,0,Flexible,Private room,2018,822,164,1,9
102030,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,1,Moderate,Private room,2015,455,91,4,36
102031,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,1,Flexible,Private room,2020,1078,216,1,58
102032,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,0,Moderate,Private room,2007,103,21,7,40
102040,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,1,Strict,Private room,2022,982,196,1,239

In [46]:
# converting the datatype to 'int'
df[['Instant_bookable','Construction year','Price','Service fee','Minimum nights','Number of reviews']]=df[['Instant_bookable','Construction year','Price','Service fee','Minimum nights','Number of reviews']].astype('int64')

C:\Users\karth\AppData\Local\Temp\ipykernel_10064\57877888.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['Instant_bookable','Construction year','Price','Service fee','Minimum nights','Number of reviews']]=df[['Instant_bookable','Construction year','Price','Service fee','Minimum nights','Number of reviews']].astype('int64')

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 99342 entries, 0 to 102040
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    99342 non-null  object
 1   Host id                 99342 non-null  int64
 2   Host_identity_verified  99342 non-null  object
 3   Host name               99342 non-null  object
 4   Neighbourhood group     99342 non-null  object
 5   Neighbourhood           99342 non-null  object
 6   Lat                     99342 non-null  float64
 7   Long                    99342 non-null  float64
 8   Country                 99342 non-null  object
 9   Country code            99342 non-null  object
 10  Instant_bookable        99342 non-null  int64
 11  Cancellation_policy     99342 non-null  object
 12  Room type               99342 non-null  object
 13  Construction year       99342 non-null  int64
 14  Price                   99342 non-null  int64
 15  Service fee             99342 non-null  int64
 16  Minimum nights          99342 non-null  int64
 17  Number of reviews       99342 non-null  int64
dtypes: float64(2), int64(7), object(9)
memory usage: 14.4+ MB

In [48]:
df.reset_index(inplace=True)
df

,index,Name,Host id,Host_identity_verified,Host name,Neighbourhood group,Neighbourhood,Lat,Long,Country,Country code,Instant_bookable,Cancellation_policy,Room type,Construction year,Price,Service fee,Minimum nights,Number of reviews
0,0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,Strict,Private room,2020,966,193,10,9
1,1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,Moderate,Entire home/apt,2007,142,28,30,45
2,4,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,Moderate,Entire home/apt,2009,204,41,10,9
3,5,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,1,Flexible,Entire home/apt,2013,577,115,3,74
4,7,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,Moderate,Private room,2009,1060,212,45,49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99337,102029,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,0,Flexible,Private room,2018,822,164,1,9
99338,102030,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,1,Moderate,Private room,2015,455,91,4,36
99339,102031,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,1,Flexible,Private room,2020,1078,216,1,58
99340,102032,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,0,Moderate,Private room,2007,103,21,7,40
99341,102040,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,1,Strict,Private room,2022,982,196,1,239

In [49]:
df.drop(columns='index',inplace=True)
df

C:\Users\karth\AppData\Local\Temp\ipykernel_10064\325572771.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns='index',inplace=True)

,Name,Host id,Host_identity_verified,Host name,Neighbourhood group,Neighbourhood,Lat,Long,Country,Country code,Instant_bookable,Cancellation_policy,Room type,Construction year,Price,Service fee,Minimum nights,Number of reviews
0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,Strict,Private room,2020,966,193,10,9
1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,Moderate,Entire home/apt,2007,142,28,30,45
2,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,Moderate,Entire home/apt,2009,204,41,10,9
3,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,1,Flexible,Entire home/apt,2013,577,115,3,74
4,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,Moderate,Private room,2009,1060,212,45,49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99337,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,0,Flexible,Private room,2018,822,164,1,9
99338,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,1,Moderate,Private room,2015,455,91,4,36
99339,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,1,Flexible,Private room,2020,1078,216,1,58
99340,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,0,Moderate,Private room,2007,103,21,7,40
99341,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,1,Strict,Private room,2022,982,196,1,239

In [50]:
df

,Name,Host id,Host_identity_verified,Host name,Neighbourhood group,Neighbourhood,Lat,Long,Country,Country code,Instant_bookable,Cancellation_policy,Room type,Construction year,Price,Service fee,Minimum nights,Number of reviews
0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,Strict,Private room,2020,966,193,10,9
1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,Moderate,Entire home/apt,2007,142,28,30,45
2,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,Moderate,Entire home/apt,2009,204,41,10,9
3,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,1,Flexible,Entire home/apt,2013,577,115,3,74
4,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,Moderate,Private room,2009,1060,212,45,49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99337,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,0,Flexible,Private room,2018,822,164,1,9
99338,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,1,Moderate,Private room,2015,455,91,4,36
99339,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,1,Flexible,Private room,2020,1078,216,1,58
99340,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,0,Moderate,Private room,2007,103,21,7,40
99341,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,1,Strict,Private room,2022,982,196,1,239

In [51]:
# replacing with '_' instead of blank space
df.columns=df.columns.str.replace(' ','_')
df

,Name,Host_id,Host_identity_verified,Host_name,Neighbourhood_group,Neighbourhood,Lat,Long,Country,Country_code,Instant_bookable,Cancellation_policy,Room_type,Construction_year,Price,Service_fee,Minimum_nights,Number_of_reviews
0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,Strict,Private room,2020,966,193,10,9
1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,0,Moderate,Entire home/apt,2007,142,28,30,45
2,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,0,Moderate,Entire home/apt,2009,204,41,10,9
3,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,1,Flexible,Entire home/apt,2013,577,115,3,74
4,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,0,Moderate,Private room,2009,1060,212,45,49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99337,Cozy room in a 2B with backyard access,5155155913,UNCONFIRMED,Cristina,Queens,Astoria,40.76987,-73.92679,United States,US,0,Flexible,Private room,2018,822,164,1,9
99338,An East Williamsburg Delight,71564706996,VERIFIED,Petra,Brooklyn,Bedford-Stuyvesant,40.68335,-73.91222,United States,US,1,Moderate,Private room,2015,455,91,4,36
99339,Cozy bedroom in williamsburg,83101851929,VERIFIED,Russell,Brooklyn,Williamsburg,40.70870,-73.96710,United States,US,1,Flexible,Private room,2020,1078,216,1,58
99340,Spacious Room w/ 2 Bed,69037598918,UNCONFIRMED,Christine,Queens,Bayside,40.75047,-73.75349,United States,US,0,Moderate,Private room,2007,103,21,7,40
99341,"Room in Queens, NY, near LGA.",56457739998,VERIFIED,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,US,1,Strict,Private room,2022,982,196,1,239

In [52]:
# saving the data to .csv
df.to_csv(r"Cleaned_Airbnb_dataset.csv")